### ISSUE TITLE
Error trying decode the visibility field

### ISSUE THREAD

**Issue by XavierCLL** [tomp/python-metar#20]
Hi,

This error show me for tha following metar code:

> SKNA 131100Z 8000 HZ FEW060 26/XX A2974 =

The error is:

```
-----------------------------------------------------------------------
METAR:  SKNA 131100Z 8000 HZ FEW060 26/XX A2974 =
-----------------------------------------------------------------------
Traceback (most recent call last):
  File "sample.py", line 90, in <module>
    obs = Metar.Metar(code)
  File "/home/xavier/python-metar/metar/Metar.py", line 413, in __init__
    raise ParserError(handler.__name__+" failed while processing '"+code+"'\n"+" ".join(err.args))
metar.Metar.ParserError: _handleWind failed while processing '8000 HZ FEW060 26/XX A2974 = '
direction must be 0..360: '800.0'
```

But the value 8000 is a visibility field not wind direction

Any idea?
Thanks

**Comment by tomp** [comment]
The regexp for the wind field matches '8000', apparently.   I've pushed an update that fixes this.  Thanks for reporting it!
